version: '3'
services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./ruby_api/tmp/postgres_data:/var/lib/postgresql
    user: postgres
    environment:
      POSTGRES_DB: bootcamp_ruby_development
      POSTGRES_USER: bootcamp_ruby
      POSTGRES_PASSWORD: bootcamp_ruby
  api:
    depends_on: 
      - db
    build: ./ruby_api
    ports:
      - 3000:3000
    volumes:
      - ./ruby_api:/app
    environment: 
      DATABASE_NAME: bootcamp_ruby_development
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_USERNAME}"
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      AWS_REGION: "${DATABASE_USERNAME}"
      AWS_ACCESS_KEY_ID: "${DATABASE_USERNAME}"
      AWS_SECRET_ACCESS_KEY: "${DATABASE_USERNAME}"
  app:
    depends_on:
      - api
    build: ./frontend
    ports: 
      - 3050:3000
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    environment:
      REACT_APP_API_HOST: api
      REACT_APP_API_PORT: 3000
    command: npm start